name: Deploy React App to S3

on:
  push:
    branches:
      - main  # Trigger workflow on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from GitHub
      - uses: actions/checkout@v3

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Install dependencies
      - run: npm install

      # 4. Run tests (optional)
      - run: npm test -- --watchAll=false || echo "Skipping tests"

      # 5. Build the React app using Parcel
      - run: npm run build

      # 6. Configure AWS credentials
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_BUCKET_REGION }}

      # 7. Deploy build folder to S3
      - run: aws s3 sync build/ s3://${{ secrets.S3_BUCKET_NAME }} --delete
